-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 17:44:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twinder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twinder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twinder` DEFAULT CHARACTER SET utf8 ;
USE `twinder` ;

-- -----------------------------------------------------
-- Table `twinder`.`twinder_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twinder`.`twinder_stats` ;

CREATE TABLE IF NOT EXISTS `twinder`.`twinder_stats` (
  `user_id` INT NOT NULL,
  `num_like` BIGINT NOT NULL DEFAULT 0,
  `num_dislike` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twinder`.`twinder_matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twinder`.`twinder_matches` ;

CREATE TABLE IF NOT EXISTS `twinder`.`twinder_matches` (
  `swipee_id` INT NOT NULL,
  `swiper_id` INT NOT NULL,
  `swipe_date` DATETIME NOT NULL DEFAULT now(),
  INDEX `Swipee` (`swipee_id` ASC) KEY_BLOCK_SIZE = 5000 INVISIBLE,
  PRIMARY KEY (`swipee_id`, `swiper_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
